#!/usr/bin/env bash
set -euo pipefail

root=${1:-harness-data}
query=${2:-catalog}
artifacts="$root/artifacts"
catalog="$root/CATALOG.md"

if [[ ! -d $artifacts ]]; then
  echo "artifact root not found: $artifacts" >&2
  exit 2
fi

rows=$(
  while IFS= read -r -d '' file; do
    id=$(sed -n '/^---$/,/^---$/p' "$file" | sed -n '2,/^---$/p' | sed -n 's/^id: *//p' | head -1)
    type=$(sed -n '/^---$/,/^---$/p' "$file" | sed -n '2,/^---$/p' | sed -n 's/^type: *//p' | head -1)
    status=$(sed -n '/^---$/,/^---$/p' "$file" | sed -n '2,/^---$/p' | sed -n 's/^status: *//p' | head -1 | sed 's/[[:space:]]*#.*$//' | xargs)
    title=$(sed -n '/^---$/,/^---$/p' "$file" | sed -n '2,/^---$/p' | sed -n 's/^title: *//p' | head -1)
    [[ -n $id && -n $type && -n $status ]] || continue
    printf '%s|%s|%s|%s\n' "$id" "$type" "$status" "${title:-}"
  done < <(
    # core v2 records; the read-only Legacy Discovery bridge
    # (harness-data/artifacts/legacy/, removed by IMPROVEMENT-0150) is excluded —
    # its records live under the enabled extension tree below.
    find "$artifacts" -type f -name '*.md' ! -path '*/questions/QUESTIONS.md' ! -path '*/legacy/*' -print0
    [[ -d "$root/extensions/legacy-discovery" ]] && \
      find "$root/extensions/legacy-discovery" -type f -name '*.md' ! -path '*/imported/*' -print0
  )
)

case "$query" in
  catalog)
    {
      printf '# Harness Catalog\n\n'
      printf '_Generated by `scripts/render-harness-views.sh`; do not edit._\n\n'
      printf '| ID | Type | Status | Title |\n| --- | --- | --- | --- |\n'
      if [[ -n $rows ]]; then
        printf '%s\n' "$rows" | LC_ALL=C sort \
          | awk -F'|' '{printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4}'
      fi
    } >"$catalog.tmp"
    mv "$catalog.tmp" "$catalog"
    ;;
  --stdout|backlinks|trace)
    printf '%s\n' "$rows" | LC_ALL=C sort
    ;;
  *)
    echo "usage: $0 [harness-data-root] [catalog|--stdout|backlinks|trace]" >&2
    exit 2
    ;;
esac
