#!/usr/bin/env bash
set -euo pipefail

root=${1:-harness-data}
query=${2:-catalog}
target=${3:-}
artifacts="$root/artifacts"
catalog="$root/CATALOG.md"

if [[ ! -d $artifacts ]]; then
  echo "artifact root not found: $artifacts" >&2
  exit 2
fi

records=$(mktemp)
edges=$(mktemp)
trap 'rm -f "$records" "$edges"' EXIT

profile_enables_legacy() {
  [[ -f $root/HARNESS-PROFILE.yaml ]] &&
    grep -qE '^[[:space:]]*legacy_discovery:[[:space:]]*enabled[[:space:]]*$' "$root/HARNESS-PROFILE.yaml"
}

frontmatter() { sed -n '/^---$/,/^---$/p' "$1"; }
scalar() {
  frontmatter "$1" | sed -n "s/^$2: *//p" | head -1 | sed 's/[[:space:]]*#.*$//' | xargs
}
array() {
  frontmatter "$1" | sed -nE "s/^$2: *\[(.*)\].*$/\1/p" | tr ',' ' ' | xargs
}

emit_record() {
  local file=$1 id type status title
  id=$(scalar "$file" id)
  type=$(scalar "$file" type)
  status=$(scalar "$file" status)
  title=$(scalar "$file" title)
  [[ -n $id && -n $type && -n $status ]] || return 0
  printf '%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s\n' \
    "$id" "$type" "$status" "$title" "$file" \
    "$(array "$file" source_ids)" "$(array "$file" related_adrs)" \
    "$(array "$file" question_refs)" "$(array "$file" included_ids)" \
    "$(array "$file" depends_on)" "$(array "$file" allowed_paths)"
}

while IFS= read -r -d '' file; do emit_record "$file"; done \
  < <(find "$artifacts" -type f -name '*.md' ! -path '*/questions/QUESTIONS.md' -print0) >"$records"
if profile_enables_legacy && [[ -d $root/extensions/legacy-discovery ]]; then
  while IFS= read -r -d '' file; do emit_record "$file"; done \
    < <(find "$root/extensions/legacy-discovery" -type f -name '*.md' ! -path '*/imported/*' -print0) >>"$records"
fi

for field_col in 'source_ids:6' 'related_adrs:7' 'question_refs:8' 'included_ids:9' 'depends_on:10'; do
  field=${field_col%%:*}; col=${field_col#*:}
  awk -F'|' -v field="$field" -v col="$col" '{n=split($col,a," "); for(i=1;i<=n;i++) if(a[i]!="") print $1 "|" field "|" a[i]}' "$records"
done >"$edges"

case "$query" in
  catalog)
    {
      printf '# Harness Catalog\n\n'
      printf '_Generated by `scripts/render-harness-views.sh`; do not edit._\n\n'
      printf '| ID | Type | Status | Title |\n| --- | --- | --- | --- |\n'
      LC_ALL=C sort -t'|' -k1,1 "$records" | awk -F'|' '{printf "| %s | %s | %s | %s |\n",$1,$2,$3,$4}'
    } >"$catalog.tmp"
    mv "$catalog.tmp" "$catalog"
    ;;
  --stdout)
    LC_ALL=C sort -t'|' -k1,1 "$records" | cut -d'|' -f1-4
    ;;
  active-plans|plan-conflicts)
    awk -F'|' -v mode="$query" '
      function shared(a,b, x,y,i,j) {
        x=split(a,aa," "); y=split(b,bb," ")
        for(i=1;i<=x;i++) for(j=1;j<=y;j++) if(aa[i]!="" && aa[i]==bb[j]) return aa[i]
        return ""
      }
      function overlap(a,b, x,y,i,j,p,q) {
        x=split(a,aa," "); y=split(b,bb," ")
        for(i=1;i<=x;i++) for(j=1;j<=y;j++) {
          p=aa[i]; q=bb[j]; sub(/\/$/,"",p); sub(/\/$/,"",q)
          if(p!="" && q!="" && (p==q || index(p,q "/")==1 || index(q,p "/")==1)) return p ":" q
        }
        return ""
      }
      $2=="task" {paths[$1]=$11; task_sources[$1]=$6}
      $2=="implementation-plan" && ($3=="ready" || $3=="in-progress") {
        plan[++n]=$1; status[n]=$3; sources[n]=$6; included[n]=$9; own_paths[n]=$11
      }
      END {
        for(i=1;i<=n;i++) {
          p=own_paths[i]; conflict_sources[i]=sources[i]; m=split(included[i],ids," ")
          for(j=1;j<=m;j++) if(paths[ids[j]]!="") p=p (p==""?"":" ") paths[ids[j]]
          for(j=1;j<=m;j++) if(task_sources[ids[j]]!="") conflict_sources[i]=conflict_sources[i] " " task_sources[ids[j]]
          m=split(sources[i],ids," ")
          for(j=1;j<=m;j++) if(task_sources[ids[j]]!="") conflict_sources[i]=conflict_sources[i] " " task_sources[ids[j]]
          plan_paths[i]=p
        }
        if(mode=="active-plans") {
          for(i=1;i<=n;i++) print plan[i] "|" status[i] "|" sources[i] "|" included[i] "|" plan_paths[i]
        } else {
          for(i=1;i<=n;i++) for(j=i+1;j<=n;j++) {
            s=shared(conflict_sources[i],conflict_sources[j]); if(s!="") print plan[i] "|" plan[j] "|same-source:" s
            p=overlap(plan_paths[i],plan_paths[j]); if(p!="") print plan[i] "|" plan[j] "|path-overlap:" p
          }
        }
      }' "$records" | LC_ALL=C sort
    ;;
  backlinks)
    [[ -n $target ]] || { echo "backlinks requires an artifact ID" >&2; exit 2; }
    awk -F'|' -v target="$target" '$3==target {print $1 "|" $2 "|" $3}' "$edges" | LC_ALL=C sort
    ;;
  trace)
    [[ -n $target ]] || { echo "trace requires an artifact ID" >&2; exit 2; }
    declare -A seen=([$target]=1)
    queue=($target)
    while ((${#queue[@]})); do
      current=${queue[0]}; queue=("${queue[@]:1}")
      while IFS='|' read -r from field to; do
        [[ $from == "$current" || $to == "$current" ]] || continue
        printf '%s|%s|%s\n' "$from" "$field" "$to"
        other=$to; [[ $to == "$current" ]] && other=$from
        if [[ -z ${seen[$other]+x} ]]; then seen[$other]=1; queue+=("$other"); fi
      done <"$edges"
    done | LC_ALL=C sort -u
    ;;
  *)
    echo "usage: $0 [harness-data-root] [catalog|--stdout|active-plans|plan-conflicts|backlinks ID|trace ID]" >&2
    exit 2
    ;;
esac
